version: '2'

services:
  camera-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc12345
    ports:
      - 5432:5432
    networks: 
      - database-network

  camera-api:
    env_file:
      - server.env
    build:
      context: ./api
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 4000:4000
      - 4001:4001
    networks: 
      - database-network

  camera-web:
    env_file:
      - server.env
    build:
      context: ./web
      args:
        - API_BASE_URL=http://192.168.2.168:4000
        - API_BROWSER_URL=http://192.168.2.168:4000
        - WS_URL=ws://192.168.2.168:4001
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 3000:3000
    networks: 
      - database-network

networks: 
  database-network:
    external: true