version: '2'

services:
  jeedoc-api:
    env_file:
      - api/.env
    build:
      context: ./api
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 4000:4000

  jeedoc-backend:
    env_file:
      - backend/.env
    build:
      context: ./backend
      args:
        - API_BASE_URL=http://192.168.1.119:4000
        - API_BROWSER_URL=http://192.168.1.119:4000
        - WS_URL=ws://192.168.1.119:4000
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 3000:3000
