version: '2'

services:
  camera-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc12345
    ports:
      - 5432:5432
    networks: 
      - database-network

  camera-api:
    env_file:
      - api/.env
    build:
      context: ./api
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - JWT_KEY=2NMbtQW4YA8j2Xxec96VQkVR7x5QkpdTJST8SsTSPba3WewY3t8ES8CTAURy3st9
      - DB_HOST=camera-db
      - DB_PORT=5432
      - DB_DATABASE=camerabuonmathuot
      - DB_USERNAME=postgres
      - DB_PASSWORD=abc12345
      - DB_SSL=false
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - PULSAR_PORT_WS=8081
      - PULSAR_TOPIC_PREFIX=non-persistent/public/default/
    ports:
      - 4000:4000
    networks: 
      - database-network

  camera-web:
    env_file:
      - web/.env
    build:
      context: ./web
      args:
        - API_BASE_URL=http://camera-api:4000
        - API_BROWSER_URL=http://192.168.1.4:4000
        - WS_URL=ws://192.168.1.4:4000
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 3000:3000
    networks: 
      - database-network

networks: 
  database-network:
    external: true