version: '2'

services:
  camera-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc12345
    ports:
      - 9003:5432
    networks: 
      - camera-network

  camera-api:
    env_file:
      - server.env
    build:
      context: ./api
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 9004:4000
    networks: 
      - database-network

  camera-web:
    env_file:
      - server.env
    build:
      context: ./web
      args:
        - API_BASE_URL=http://115.79.28.221:9004
        - API_BROWSER_URL=http://115.79.28.221:9004
        - WS_URL=ws://115.79.28.221:9004
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 9005:3000
    networks: 
      - database-network

networks: 
  database-network:
    external: true